os:
  - linux
  - windows
  - mac
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  #- rustfmt --check src/*.rs
  - cargo build --release
